name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Verify SSH connection
        run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} github-deploy@${{ secrets.DROPLET_IP }} "echo Connection successful"

      - name: Create DB backup
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: github-deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/backups
            pg_dump -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f ~/backups/backup_$(date +%Y%m%d_%H%M%S).sql

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: github-deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e 
            pwd
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            npm install
            npm run migrate

      - name: Upload build files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: github-deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".next/,public/,package.json"
          target: "${{ secrets.PROJECT_PATH }}"
          strip_components: 0
          overwrite: true

      - name: Restart application
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: github-deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: pm2 restart ${{ secrets.PM2_APP_NAME }}
